version: 0.2

phases:
  install:
    commands:
      - echo Installing Java 17...
      - apt-get update && apt-get install -y openjdk-17-jdk
      - echo Installing Java Maven...
      - apt-get install -y maven
      - echo Installing AWS CLI...
      - apt-get install -y python3-pip
      - sudo pip3 install awscli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Java project...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t my-app .
      - echo Pushing the Docker image...
      - docker tag my-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPO_NAME:latest
      # Additional build commands can be added here

  post_build:
    commands:
      - echo Running post-build actions...
      # Additional post-build commands can be added here

artifacts:
  files:
    - target/awsCICD-0.0.1-SNAPSHOT.jar
  discard-paths: yes
